# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.problem_details_dto import ProblemDetailsDto
from ..types.scan_dto import ScanDto
from ..types.seed_mail_result_dto import SeedMailResultDto
from ..types.seed_result_dto import SeedResultDto
from .types.seed_sandbox_mail_dto_mail_type import SeedSandboxMailDtoMailType
from .types.seed_sandbox_mail_dto_measurement import SeedSandboxMailDtoMeasurement
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSandboxClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def seed(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[SeedResultDto]:
        """
        Populate your sandbox mailbox with sample mail items for testing

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SeedResultDto]

        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/sandbox/seed",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SeedResultDto,
                    parse_obj_as(
                        type_=SeedResultDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def seedmail(
        self,
        *,
        sender_name: typing.Optional[str] = OMIT,
        mail_type: typing.Optional[SeedSandboxMailDtoMailType] = OMIT,
        weight: typing.Optional[float] = OMIT,
        measurement: typing.Optional[SeedSandboxMailDtoMeasurement] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SeedMailResultDto]:
        """
        Add one sample mail item to your sandbox mailbox, with optional overrides

        Parameters
        ----------
        sender_name : typing.Optional[str]

        mail_type : typing.Optional[SeedSandboxMailDtoMailType]
            Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.

        weight : typing.Optional[float]
            Item weight, in pounds.

        measurement : typing.Optional[SeedSandboxMailDtoMeasurement]
            Item dimensions, in inches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SeedMailResultDto]

        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/sandbox/seed/mail",
            method="POST",
            json={
                "sender_name": sender_name,
                "mail_type": mail_type,
                "weight": weight,
                "measurement": convert_and_respect_annotation_metadata(
                    object_=measurement, annotation=SeedSandboxMailDtoMeasurement, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SeedMailResultDto,
                    parse_obj_as(
                        type_=SeedMailResultDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def completescan(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        summary: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ScanDto]:
        """
        Force a pending scan to completed in the sandbox for testing

        Parameters
        ----------
        id : str

        label : typing.Optional[str]
            Short document label the AI would produce, e.g. "Insurance". Set on the scan.

        summary : typing.Optional[typing.Sequence[str]]
            Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ScanDto]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/sandbox/scans/{jsonable_encoder(id)}/complete",
            method="POST",
            json={
                "label": label,
                "summary": summary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ScanDto,
                    parse_obj_as(
                        type_=ScanDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSandboxClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def seed(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SeedResultDto]:
        """
        Populate your sandbox mailbox with sample mail items for testing

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SeedResultDto]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/sandbox/seed",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SeedResultDto,
                    parse_obj_as(
                        type_=SeedResultDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def seedmail(
        self,
        *,
        sender_name: typing.Optional[str] = OMIT,
        mail_type: typing.Optional[SeedSandboxMailDtoMailType] = OMIT,
        weight: typing.Optional[float] = OMIT,
        measurement: typing.Optional[SeedSandboxMailDtoMeasurement] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SeedMailResultDto]:
        """
        Add one sample mail item to your sandbox mailbox, with optional overrides

        Parameters
        ----------
        sender_name : typing.Optional[str]

        mail_type : typing.Optional[SeedSandboxMailDtoMailType]
            Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.

        weight : typing.Optional[float]
            Item weight, in pounds.

        measurement : typing.Optional[SeedSandboxMailDtoMeasurement]
            Item dimensions, in inches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SeedMailResultDto]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/sandbox/seed/mail",
            method="POST",
            json={
                "sender_name": sender_name,
                "mail_type": mail_type,
                "weight": weight,
                "measurement": convert_and_respect_annotation_metadata(
                    object_=measurement, annotation=SeedSandboxMailDtoMeasurement, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SeedMailResultDto,
                    parse_obj_as(
                        type_=SeedMailResultDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def completescan(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        summary: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ScanDto]:
        """
        Force a pending scan to completed in the sandbox for testing

        Parameters
        ----------
        id : str

        label : typing.Optional[str]
            Short document label the AI would produce, e.g. "Insurance". Set on the scan.

        summary : typing.Optional[typing.Sequence[str]]
            Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ScanDto]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/sandbox/scans/{jsonable_encoder(id)}/complete",
            method="POST",
            json={
                "label": label,
                "summary": summary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ScanDto,
                    parse_obj_as(
                        type_=ScanDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ProblemDetailsDto,
                        parse_obj_as(
                            type_=ProblemDetailsDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
