# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.scan_dto import ScanDto
from ..types.seed_mail_result_dto import SeedMailResultDto
from ..types.seed_result_dto import SeedResultDto
from .raw_client import AsyncRawSandboxClient, RawSandboxClient
from .types.seed_sandbox_mail_dto_mail_type import SeedSandboxMailDtoMailType
from .types.seed_sandbox_mail_dto_measurement import SeedSandboxMailDtoMeasurement

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxClient
        """
        return self._raw_client

    def seed(self, *, request_options: typing.Optional[RequestOptions] = None) -> SeedResultDto:
        """
        Populate your sandbox mailbox with sample mail items for testing

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SeedResultDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.sandbox.seed()
        """
        _response = self._raw_client.seed(request_options=request_options)
        return _response.data

    def seedmail(
        self,
        *,
        sender_name: typing.Optional[str] = OMIT,
        mail_type: typing.Optional[SeedSandboxMailDtoMailType] = OMIT,
        weight: typing.Optional[float] = OMIT,
        measurement: typing.Optional[SeedSandboxMailDtoMeasurement] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SeedMailResultDto:
        """
        Add one sample mail item to your sandbox mailbox, with optional overrides

        Parameters
        ----------
        sender_name : typing.Optional[str]

        mail_type : typing.Optional[SeedSandboxMailDtoMailType]
            Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.

        weight : typing.Optional[float]
            Item weight, in pounds.

        measurement : typing.Optional[SeedSandboxMailDtoMeasurement]
            Item dimensions, in inches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SeedMailResultDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.sandbox.seedmail()
        """
        _response = self._raw_client.seedmail(
            sender_name=sender_name,
            mail_type=mail_type,
            weight=weight,
            measurement=measurement,
            request_options=request_options,
        )
        return _response.data

    def completescan(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        summary: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanDto:
        """
        Force a pending scan to completed in the sandbox for testing

        Parameters
        ----------
        id : str

        label : typing.Optional[str]
            Short document label the AI would produce, e.g. "Insurance". Set on the scan.

        summary : typing.Optional[typing.Sequence[str]]
            Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.sandbox.completescan(
            id="id",
        )
        """
        _response = self._raw_client.completescan(id, label=label, summary=summary, request_options=request_options)
        return _response.data


class AsyncSandboxClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxClient
        """
        return self._raw_client

    async def seed(self, *, request_options: typing.Optional[RequestOptions] = None) -> SeedResultDto:
        """
        Populate your sandbox mailbox with sample mail items for testing

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SeedResultDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.sandbox.seed()


        asyncio.run(main())
        """
        _response = await self._raw_client.seed(request_options=request_options)
        return _response.data

    async def seedmail(
        self,
        *,
        sender_name: typing.Optional[str] = OMIT,
        mail_type: typing.Optional[SeedSandboxMailDtoMailType] = OMIT,
        weight: typing.Optional[float] = OMIT,
        measurement: typing.Optional[SeedSandboxMailDtoMeasurement] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SeedMailResultDto:
        """
        Add one sample mail item to your sandbox mailbox, with optional overrides

        Parameters
        ----------
        sender_name : typing.Optional[str]

        mail_type : typing.Optional[SeedSandboxMailDtoMailType]
            Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.

        weight : typing.Optional[float]
            Item weight, in pounds.

        measurement : typing.Optional[SeedSandboxMailDtoMeasurement]
            Item dimensions, in inches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SeedMailResultDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.sandbox.seedmail()


        asyncio.run(main())
        """
        _response = await self._raw_client.seedmail(
            sender_name=sender_name,
            mail_type=mail_type,
            weight=weight,
            measurement=measurement,
            request_options=request_options,
        )
        return _response.data

    async def completescan(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        summary: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanDto:
        """
        Force a pending scan to completed in the sandbox for testing

        Parameters
        ----------
        id : str

        label : typing.Optional[str]
            Short document label the AI would produce, e.g. "Insurance". Set on the scan.

        summary : typing.Optional[typing.Sequence[str]]
            Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.sandbox.completescan(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.completescan(
            id, label=label, summary=summary, request_options=request_options
        )
        return _response.data
