# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.address_dto import AddressDto
from ..types.address_page_dto import AddressPageDto
from .raw_client import AsyncRawAddressesClient, RawAddressesClient
from .types.addresses_get_default_request_type import AddressesGetDefaultRequestType
from .types.addresses_list_request_type import AddressesListRequestType
from .types.create_address_dto_type import CreateAddressDtoType
from .types.update_address_dto_type import UpdateAddressDtoType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AddressesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAddressesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAddressesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAddressesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        type: typing.Optional[AddressesListRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressPageDto:
        """
        List your shipping and deposit addresses, optionally filtered by type

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        type : typing.Optional[AddressesListRequestType]
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressPageDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.list()
        """
        _response = self._raw_client.list(limit=limit, cursor=cursor, type=type, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        type: CreateAddressDtoType,
        name: str,
        line1: str,
        city: str,
        state: str,
        postal_code: str,
        country: str,
        phone_number: str,
        line2: typing.Optional[str] = OMIT,
        line3: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressDto:
        """
        Add a new shipping or check-deposit address to your account

        Parameters
        ----------
        type : CreateAddressDtoType
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        name : str

        line1 : str

        city : str

        state : str

        postal_code : str

        country : str

        phone_number : str

        line2 : typing.Optional[str]

        line3 : typing.Optional[str]

        tax_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.create(
            type="shipping",
            name="name",
            line1="line1",
            city="city",
            state="state",
            postal_code="postal_code",
            country="country",
            phone_number="phone_number",
        )
        """
        _response = self._raw_client.create(
            type=type,
            name=name,
            line1=line1,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            phone_number=phone_number,
            line2=line2,
            line3=line3,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    def getdefault(
        self, *, type: AddressesGetDefaultRequestType, request_options: typing.Optional[RequestOptions] = None
    ) -> AddressDto:
        """
        Get your default address for a given type, shipping or deposit

        Parameters
        ----------
        type : AddressesGetDefaultRequestType
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.getdefault(
            type="shipping",
        )
        """
        _response = self._raw_client.getdefault(type=type, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AddressDto:
        """
        Retrieve one shipping or deposit address by its id

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently delete an address; this is destructive and cannot be undone

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        type: typing.Optional[UpdateAddressDtoType] = OMIT,
        name: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        line3: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressDto:
        """
        Update fields on an existing shipping or deposit address

        Parameters
        ----------
        id : str

        type : typing.Optional[UpdateAddressDtoType]
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        name : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        line3 : typing.Optional[str]

        city : typing.Optional[str]

        state : typing.Optional[str]

        postal_code : typing.Optional[str]

        country : typing.Optional[str]

        phone_number : typing.Optional[str]

        tax_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            type=type,
            name=name,
            line1=line1,
            line2=line2,
            line3=line3,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            phone_number=phone_number,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    def setdefault(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AddressDto:
        """
        Make this address the default for its type, replacing the previous default

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.addresses.setdefault(
            id="id",
        )
        """
        _response = self._raw_client.setdefault(id, request_options=request_options)
        return _response.data


class AsyncAddressesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAddressesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAddressesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAddressesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        type: typing.Optional[AddressesListRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressPageDto:
        """
        List your shipping and deposit addresses, optionally filtered by type

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        type : typing.Optional[AddressesListRequestType]
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressPageDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, cursor=cursor, type=type, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        type: CreateAddressDtoType,
        name: str,
        line1: str,
        city: str,
        state: str,
        postal_code: str,
        country: str,
        phone_number: str,
        line2: typing.Optional[str] = OMIT,
        line3: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressDto:
        """
        Add a new shipping or check-deposit address to your account

        Parameters
        ----------
        type : CreateAddressDtoType
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        name : str

        line1 : str

        city : str

        state : str

        postal_code : str

        country : str

        phone_number : str

        line2 : typing.Optional[str]

        line3 : typing.Optional[str]

        tax_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.create(
                type="shipping",
                name="name",
                line1="line1",
                city="city",
                state="state",
                postal_code="postal_code",
                country="country",
                phone_number="phone_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            type=type,
            name=name,
            line1=line1,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            phone_number=phone_number,
            line2=line2,
            line3=line3,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    async def getdefault(
        self, *, type: AddressesGetDefaultRequestType, request_options: typing.Optional[RequestOptions] = None
    ) -> AddressDto:
        """
        Get your default address for a given type, shipping or deposit

        Parameters
        ----------
        type : AddressesGetDefaultRequestType
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.getdefault(
                type="shipping",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.getdefault(type=type, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AddressDto:
        """
        Retrieve one shipping or deposit address by its id

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently delete an address; this is destructive and cannot be undone

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        type: typing.Optional[UpdateAddressDtoType] = OMIT,
        name: typing.Optional[str] = OMIT,
        line1: typing.Optional[str] = OMIT,
        line2: typing.Optional[str] = OMIT,
        line3: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        postal_code: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddressDto:
        """
        Update fields on an existing shipping or deposit address

        Parameters
        ----------
        id : str

        type : typing.Optional[UpdateAddressDtoType]
            `shipping` = a shipment destination; `deposit` = where check deposits are sent.

        name : typing.Optional[str]

        line1 : typing.Optional[str]

        line2 : typing.Optional[str]

        line3 : typing.Optional[str]

        city : typing.Optional[str]

        state : typing.Optional[str]

        postal_code : typing.Optional[str]

        country : typing.Optional[str]

        phone_number : typing.Optional[str]

        tax_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            type=type,
            name=name,
            line1=line1,
            line2=line2,
            line3=line3,
            city=city,
            state=state,
            postal_code=postal_code,
            country=country,
            phone_number=phone_number,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    async def setdefault(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AddressDto:
        """
        Make this address the default for its type, replacing the previous default

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.addresses.setdefault(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.setdefault(id, request_options=request_options)
        return _response.data
