# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .account_dto import AccountDto
    from .address_dto import AddressDto
    from .address_dto_type import AddressDtoType
    from .address_page_dto import AddressPageDto
    from .address_page_dto_data_item import AddressPageDtoDataItem
    from .address_page_dto_data_item_type import AddressPageDtoDataItemType
    from .bank_account_dto import BankAccountDto
    from .bank_account_page_dto import BankAccountPageDto
    from .bank_account_page_dto_data_item import BankAccountPageDtoDataItem
    from .folder_dto import FolderDto
    from .folder_list_dto import FolderListDto
    from .folder_list_dto_data_item import FolderListDtoDataItem
    from .mail_detail_dto import MailDetailDto
    from .mail_detail_dto_folder import MailDetailDtoFolder
    from .mail_detail_dto_measurement import MailDetailDtoMeasurement
    from .mail_detail_dto_scan import MailDetailDtoScan
    from .mail_page_dto import MailPageDto
    from .mail_page_dto_data_item import MailPageDtoDataItem
    from .mail_page_dto_data_item_scan import MailPageDtoDataItemScan
    from .mailing_address_dto import MailingAddressDto
    from .problem_details_dto import ProblemDetailsDto
    from .problem_details_dto_errors_item import ProblemDetailsDtoErrorsItem
    from .scan_dto import ScanDto
    from .scan_file_dto import ScanFileDto
    from .scan_page_dto import ScanPageDto
    from .scan_page_dto_data_item import ScanPageDtoDataItem
    from .scan_summary_dto import ScanSummaryDto
    from .seed_mail_result_dto import SeedMailResultDto
    from .seed_result_dto import SeedResultDto
    from .shipment_detail_dto import ShipmentDetailDto
    from .shipment_detail_dto_destination import ShipmentDetailDtoDestination
    from .shipment_detail_dto_mail_items_item import ShipmentDetailDtoMailItemsItem
    from .shipment_detail_dto_status import ShipmentDetailDtoStatus
    from .shipment_detail_dto_type import ShipmentDetailDtoType
    from .shipment_page_dto import ShipmentPageDto
    from .shipment_page_dto_data_item import ShipmentPageDtoDataItem
    from .shipment_page_dto_data_item_destination import ShipmentPageDtoDataItemDestination
    from .shipment_page_dto_data_item_status import ShipmentPageDtoDataItemStatus
    from .shipment_page_dto_data_item_type import ShipmentPageDtoDataItemType
_dynamic_imports: typing.Dict[str, str] = {
    "AccountDto": ".account_dto",
    "AddressDto": ".address_dto",
    "AddressDtoType": ".address_dto_type",
    "AddressPageDto": ".address_page_dto",
    "AddressPageDtoDataItem": ".address_page_dto_data_item",
    "AddressPageDtoDataItemType": ".address_page_dto_data_item_type",
    "BankAccountDto": ".bank_account_dto",
    "BankAccountPageDto": ".bank_account_page_dto",
    "BankAccountPageDtoDataItem": ".bank_account_page_dto_data_item",
    "FolderDto": ".folder_dto",
    "FolderListDto": ".folder_list_dto",
    "FolderListDtoDataItem": ".folder_list_dto_data_item",
    "MailDetailDto": ".mail_detail_dto",
    "MailDetailDtoFolder": ".mail_detail_dto_folder",
    "MailDetailDtoMeasurement": ".mail_detail_dto_measurement",
    "MailDetailDtoScan": ".mail_detail_dto_scan",
    "MailPageDto": ".mail_page_dto",
    "MailPageDtoDataItem": ".mail_page_dto_data_item",
    "MailPageDtoDataItemScan": ".mail_page_dto_data_item_scan",
    "MailingAddressDto": ".mailing_address_dto",
    "ProblemDetailsDto": ".problem_details_dto",
    "ProblemDetailsDtoErrorsItem": ".problem_details_dto_errors_item",
    "ScanDto": ".scan_dto",
    "ScanFileDto": ".scan_file_dto",
    "ScanPageDto": ".scan_page_dto",
    "ScanPageDtoDataItem": ".scan_page_dto_data_item",
    "ScanSummaryDto": ".scan_summary_dto",
    "SeedMailResultDto": ".seed_mail_result_dto",
    "SeedResultDto": ".seed_result_dto",
    "ShipmentDetailDto": ".shipment_detail_dto",
    "ShipmentDetailDtoDestination": ".shipment_detail_dto_destination",
    "ShipmentDetailDtoMailItemsItem": ".shipment_detail_dto_mail_items_item",
    "ShipmentDetailDtoStatus": ".shipment_detail_dto_status",
    "ShipmentDetailDtoType": ".shipment_detail_dto_type",
    "ShipmentPageDto": ".shipment_page_dto",
    "ShipmentPageDtoDataItem": ".shipment_page_dto_data_item",
    "ShipmentPageDtoDataItemDestination": ".shipment_page_dto_data_item_destination",
    "ShipmentPageDtoDataItemStatus": ".shipment_page_dto_data_item_status",
    "ShipmentPageDtoDataItemType": ".shipment_page_dto_data_item_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AccountDto",
    "AddressDto",
    "AddressDtoType",
    "AddressPageDto",
    "AddressPageDtoDataItem",
    "AddressPageDtoDataItemType",
    "BankAccountDto",
    "BankAccountPageDto",
    "BankAccountPageDtoDataItem",
    "FolderDto",
    "FolderListDto",
    "FolderListDtoDataItem",
    "MailDetailDto",
    "MailDetailDtoFolder",
    "MailDetailDtoMeasurement",
    "MailDetailDtoScan",
    "MailPageDto",
    "MailPageDtoDataItem",
    "MailPageDtoDataItemScan",
    "MailingAddressDto",
    "ProblemDetailsDto",
    "ProblemDetailsDtoErrorsItem",
    "ScanDto",
    "ScanFileDto",
    "ScanPageDto",
    "ScanPageDtoDataItem",
    "ScanSummaryDto",
    "SeedMailResultDto",
    "SeedResultDto",
    "ShipmentDetailDto",
    "ShipmentDetailDtoDestination",
    "ShipmentDetailDtoMailItemsItem",
    "ShipmentDetailDtoStatus",
    "ShipmentDetailDtoType",
    "ShipmentPageDto",
    "ShipmentPageDtoDataItem",
    "ShipmentPageDtoDataItemDestination",
    "ShipmentPageDtoDataItemStatus",
    "ShipmentPageDtoDataItemType",
]
