# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FolderDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Folder id (numeric string) — mail items reference it as `folder_id`.
    """

    name: str
    color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex color like `#4BB94B`.
    """

    created_on: dt.datetime
    updated_on: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
