# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MailingAddressDto(UniversalBaseModel):
    box_number: str = pydantic.Field()
    """
    The PMB (private mailbox) number — include it on every inbound mail piece.
    """

    line1: typing.Optional[str] = None
    line2: typing.Optional[str] = None
    line3: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    postal_code: typing.Optional[str] = None
    country: typing.Optional[str] = None
    formatted: str = pydantic.Field()
    """
    The complete address on one line, ready to hand out: "<line1> PMB <box>, <city>, <state>, <postal_code>, <country>".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
