# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ScanSummaryDto(UniversalBaseModel):
    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short AI-generated label of the document (e.g. "Insurance").
    """

    summary: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    AI-generated summary of the document contents, one bullet point per entry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
