# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .shipment_page_dto_data_item_destination import ShipmentPageDtoDataItemDestination
from .shipment_page_dto_data_item_status import ShipmentPageDtoDataItemStatus
from .shipment_page_dto_data_item_type import ShipmentPageDtoDataItemType


class ShipmentPageDtoDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Shipment id (UUID).
    """

    type: ShipmentPageDtoDataItemType
    status: ShipmentPageDtoDataItemStatus = pydantic.Field()
    """
    Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment.
    """

    tracking_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier tracking number, once the shipment is on its way.
    """

    service_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier service used (e.g. "FedEx International Priority").
    """

    destination: typing.Optional[ShipmentPageDtoDataItemDestination] = pydantic.Field(default=None)
    """
    Where it ships to. Only present for `shipment` and `check_deposit` types — returns go back to the sender and pickups happen at the facility.
    """

    item_count: int = pydantic.Field()
    """
    Number of mail items packed into the request.
    """

    requested_ship_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The ship-out date the customer asked for.
    """

    created_on: dt.datetime = pydantic.Field()
    """
    When the request was made.
    """

    deposit_check_slip_company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    `check_deposit` only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
