# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_scan_dto_type import CreateScanDtoType
    from .scans_list_request_scanned import ScansListRequestScanned
    from .scans_list_request_sort import ScansListRequestSort
    from .scans_list_request_status_item import ScansListRequestStatusItem
    from .scans_list_request_type_item import ScansListRequestTypeItem
_dynamic_imports: typing.Dict[str, str] = {
    "CreateScanDtoType": ".create_scan_dto_type",
    "ScansListRequestScanned": ".scans_list_request_scanned",
    "ScansListRequestSort": ".scans_list_request_sort",
    "ScansListRequestStatusItem": ".scans_list_request_status_item",
    "ScansListRequestTypeItem": ".scans_list_request_type_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateScanDtoType",
    "ScansListRequestScanned",
    "ScansListRequestSort",
    "ScansListRequestStatusItem",
    "ScansListRequestTypeItem",
]
