# This file was auto-generated by Fern from our API Definition.

import typing

ScansListRequestStatusItem = typing.Union[
    typing.Literal["submitted", "in_process", "cancelled", "rejected", "completed", "deleted", "restoring"], typing.Any
]
