# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.account_dto import AccountDto
from ..types.mailing_address_dto import MailingAddressDto
from .raw_client import AsyncRawAccountClient, RawAccountClient


class AccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAccountClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> AccountDto:
        """
        Your account profile, including name, email, status, and PMB number

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.account.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def mailingaddress(self, *, request_options: typing.Optional[RequestOptions] = None) -> MailingAddressDto:
        """
        Your current USGM address, including PMB number

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MailingAddressDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.account.mailingaddress()
        """
        _response = self._raw_client.mailingaddress(request_options=request_options)
        return _response.data


class AsyncAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAccountClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> AccountDto:
        """
        Your account profile, including name, email, status, and PMB number

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.account.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def mailingaddress(self, *, request_options: typing.Optional[RequestOptions] = None) -> MailingAddressDto:
        """
        Your current USGM address, including PMB number

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MailingAddressDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.account.mailingaddress()


        asyncio.run(main())
        """
        _response = await self._raw_client.mailingaddress(request_options=request_options)
        return _response.data
