# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.scan_dto import ScanDto
from ..types.scan_file_dto import ScanFileDto
from ..types.scan_page_dto import ScanPageDto
from ..types.scan_summary_dto import ScanSummaryDto
from .raw_client import AsyncRawScansClient, RawScansClient
from .types.create_scan_dto_type import CreateScanDtoType
from .types.scans_list_request_scanned import ScansListRequestScanned
from .types.scans_list_request_sort import ScansListRequestSort
from .types.scans_list_request_status_item import ScansListRequestStatusItem
from .types.scans_list_request_type_item import ScansListRequestTypeItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ScansClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawScansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawScansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawScansClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[
            typing.Union[ScansListRequestStatusItem, typing.Sequence[ScansListRequestStatusItem]]
        ] = None,
        type: typing.Optional[typing.Union[ScansListRequestTypeItem, typing.Sequence[ScansListRequestTypeItem]]] = None,
        mail_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[ScansListRequestSort] = None,
        scanned: typing.Optional[ScansListRequestScanned] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanPageDto:
        """
        List your scan and open-and-scan requests, with filtering, search and pagination

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        status : typing.Optional[typing.Union[ScansListRequestStatusItem, typing.Sequence[ScansListRequestStatusItem]]]

        type : typing.Optional[typing.Union[ScansListRequestTypeItem, typing.Sequence[ScansListRequestTypeItem]]]
            `scan` (scan the item) or `open` (open it and scan the contents).

        mail_id : typing.Optional[str]

        search : typing.Optional[str]

        sort : typing.Optional[ScansListRequestSort]

        scanned : typing.Optional[ScansListRequestScanned]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanPageDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.list()
        """
        _response = self._raw_client.list(
            limit=limit,
            cursor=cursor,
            status=status,
            type=type,
            mail_id=mail_id,
            search=search,
            sort=sort,
            scanned=scanned,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        mail_id: str,
        type: CreateScanDtoType,
        instruction: typing.Optional[str] = OMIT,
        is_expedited: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanDto:
        """
        Request a scan or open-and-scan of a mail item; this is a billable action

        Parameters
        ----------
        mail_id : str

        type : CreateScanDtoType
            `scan` scans the item as-is; `open` opens it and scans the contents.

        instruction : typing.Optional[str]

        is_expedited : typing.Optional[bool]
            Expedited handling — may incur an extra charge.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.create(
            mail_id="mail_id",
            type="scan",
        )
        """
        _response = self._raw_client.create(
            mail_id=mail_id,
            type=type,
            instruction=instruction,
            is_expedited=is_expedited,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Retrieve one scan request by its id, including status and AI label

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Permanently delete a scan and remove its stored file; this cannot be undone

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def file(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanFileDto:
        """
        Return a short-lived signed URL to download the scanned document; fetch it promptly

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanFileDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.file(
            id="id",
        )
        """
        _response = self._raw_client.file(id, request_options=request_options)
        return _response.data

    def summary(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanSummaryDto:
        """
        Return the AI-generated label and bullet summary of the scanned document

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanSummaryDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.summary(
            id="id",
        )
        """
        _response = self._raw_client.summary(id, request_options=request_options)
        return _response.data

    def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Cancel a scan request you no longer need. Valid only for scan requests in in_process status

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.scans.cancel(
            id="id",
        )
        """
        _response = self._raw_client.cancel(id, request_options=request_options)
        return _response.data


class AsyncScansClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawScansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawScansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawScansClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[
            typing.Union[ScansListRequestStatusItem, typing.Sequence[ScansListRequestStatusItem]]
        ] = None,
        type: typing.Optional[typing.Union[ScansListRequestTypeItem, typing.Sequence[ScansListRequestTypeItem]]] = None,
        mail_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[ScansListRequestSort] = None,
        scanned: typing.Optional[ScansListRequestScanned] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanPageDto:
        """
        List your scan and open-and-scan requests, with filtering, search and pagination

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        status : typing.Optional[typing.Union[ScansListRequestStatusItem, typing.Sequence[ScansListRequestStatusItem]]]

        type : typing.Optional[typing.Union[ScansListRequestTypeItem, typing.Sequence[ScansListRequestTypeItem]]]
            `scan` (scan the item) or `open` (open it and scan the contents).

        mail_id : typing.Optional[str]

        search : typing.Optional[str]

        sort : typing.Optional[ScansListRequestSort]

        scanned : typing.Optional[ScansListRequestScanned]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanPageDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit,
            cursor=cursor,
            status=status,
            type=type,
            mail_id=mail_id,
            search=search,
            sort=sort,
            scanned=scanned,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        mail_id: str,
        type: CreateScanDtoType,
        instruction: typing.Optional[str] = OMIT,
        is_expedited: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScanDto:
        """
        Request a scan or open-and-scan of a mail item; this is a billable action

        Parameters
        ----------
        mail_id : str

        type : CreateScanDtoType
            `scan` scans the item as-is; `open` opens it and scans the contents.

        instruction : typing.Optional[str]

        is_expedited : typing.Optional[bool]
            Expedited handling — may incur an extra charge.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.create(
                mail_id="mail_id",
                type="scan",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            mail_id=mail_id,
            type=type,
            instruction=instruction,
            is_expedited=is_expedited,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Retrieve one scan request by its id, including status and AI label

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Permanently delete a scan and remove its stored file; this cannot be undone

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def file(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanFileDto:
        """
        Return a short-lived signed URL to download the scanned document; fetch it promptly

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanFileDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.file(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.file(id, request_options=request_options)
        return _response.data

    async def summary(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanSummaryDto:
        """
        Return the AI-generated label and bullet summary of the scanned document

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanSummaryDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.summary(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.summary(id, request_options=request_options)
        return _response.data

    async def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScanDto:
        """
        Cancel a scan request you no longer need. Valid only for scan requests in in_process status

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScanDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.scans.cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, request_options=request_options)
        return _response.data
