# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.shipment_detail_dto import ShipmentDetailDto
from ..types.shipment_page_dto import ShipmentPageDto
from .raw_client import AsyncRawShipmentsClient, RawShipmentsClient
from .types.shipments_list_request_status_item import ShipmentsListRequestStatusItem
from .types.shipments_list_request_type_item import ShipmentsListRequestTypeItem


class ShipmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawShipmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawShipmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawShipmentsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        type: typing.Optional[
            typing.Union[ShipmentsListRequestTypeItem, typing.Sequence[ShipmentsListRequestTypeItem]]
        ] = None,
        status: typing.Optional[
            typing.Union[ShipmentsListRequestStatusItem, typing.Sequence[ShipmentsListRequestStatusItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShipmentPageDto:
        """
        Read-only list of your shipment requests, filterable by type and status

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        type : typing.Optional[typing.Union[ShipmentsListRequestTypeItem, typing.Sequence[ShipmentsListRequestTypeItem]]]

        status : typing.Optional[typing.Union[ShipmentsListRequestStatusItem, typing.Sequence[ShipmentsListRequestStatusItem]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShipmentPageDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.shipments.list()
        """
        _response = self._raw_client.list(
            limit=limit, cursor=cursor, type=type, status=status, request_options=request_options
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ShipmentDetailDto:
        """
        Read-only details of one shipment, including its packed mail items

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShipmentDetailDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.shipments.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncShipmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawShipmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawShipmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawShipmentsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        type: typing.Optional[
            typing.Union[ShipmentsListRequestTypeItem, typing.Sequence[ShipmentsListRequestTypeItem]]
        ] = None,
        status: typing.Optional[
            typing.Union[ShipmentsListRequestStatusItem, typing.Sequence[ShipmentsListRequestStatusItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShipmentPageDto:
        """
        Read-only list of your shipment requests, filterable by type and status

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, capped at 100.

        cursor : typing.Optional[str]
            Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.

        type : typing.Optional[typing.Union[ShipmentsListRequestTypeItem, typing.Sequence[ShipmentsListRequestTypeItem]]]

        status : typing.Optional[typing.Union[ShipmentsListRequestStatusItem, typing.Sequence[ShipmentsListRequestStatusItem]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShipmentPageDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.shipments.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit, cursor=cursor, type=type, status=status, request_options=request_options
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ShipmentDetailDto:
        """
        Read-only details of one shipment, including its packed mail items

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShipmentDetailDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.shipments.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
