# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.folder_dto import FolderDto
from ..types.folder_list_dto import FolderListDto
from .raw_client import AsyncRawFoldersClient, RawFoldersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FoldersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFoldersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFoldersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFoldersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> FolderListDto:
        """
        All your mail folders, returned unpaginated

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderListDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.folders.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self, *, name: str, color: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> FolderDto:
        """
        Create a new mail folder with a name and optional color

        Parameters
        ----------
        name : str

        color : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.folders.create(
            name="name",
        )
        """
        _response = self._raw_client.create(name=name, color=color, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> FolderDto:
        """
        Retrieve one mail folder by its id

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.folders.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a folder and unfile its mail, which is not deleted

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.folders.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        color: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FolderDto:
        """
        Rename a folder or change its color

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        color : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        from usgm import Usgm

        client = Usgm(
            token="YOUR_TOKEN",
        )
        client.folders.update(
            id="id",
        )
        """
        _response = self._raw_client.update(id, name=name, color=color, request_options=request_options)
        return _response.data


class AsyncFoldersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFoldersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFoldersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFoldersClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> FolderListDto:
        """
        All your mail folders, returned unpaginated

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderListDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.folders.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self, *, name: str, color: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> FolderDto:
        """
        Create a new mail folder with a name and optional color

        Parameters
        ----------
        name : str

        color : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.folders.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(name=name, color=color, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> FolderDto:
        """
        Retrieve one mail folder by its id

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.folders.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a folder and unfile its mail, which is not deleted

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.folders.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        color: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FolderDto:
        """
        Rename a folder or change its color

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        color : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FolderDto


        Examples
        --------
        import asyncio

        from usgm import AsyncUsgm

        client = AsyncUsgm(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.folders.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, name=name, color=color, request_options=request_options)
        return _response.data
