# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .address_page_dto_data_item_type import AddressPageDtoDataItemType


class AddressPageDtoDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Address id (UUID).
    """

    type: AddressPageDtoDataItemType = pydantic.Field()
    """
    `shipping` = a shipment destination; `deposit` = where check deposits are sent.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recipient name on the address.
    """

    line1: typing.Optional[str] = None
    line2: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    postal_code: typing.Optional[str] = None
    country: typing.Optional[str] = None
    line3: typing.Optional[str] = None
    phone_number: typing.Optional[str] = None
    tax_id: typing.Optional[str] = None
    is_default: bool = pydantic.Field()
    """
    The default address of its `type` — one per type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
