# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BankAccountPageDtoDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Bank account id (UUID).
    """

    bank_name: str
    bank_state: str
    account_number_last4: str = pydantic.Field()
    """
    Last 4 characters of the account number. The full number is write-only and never returned.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
