# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bank_account_page_dto_data_item import BankAccountPageDtoDataItem


class BankAccountPageDto(UniversalBaseModel):
    data: typing.List[BankAccountPageDtoDataItem]
    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pass as `?cursor=` to fetch the next page. Null on the last page.
    """

    total_count: int = pydantic.Field()
    """
    Total number of items matching this query across all pages.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
