# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mail_page_dto_data_item_scan import MailPageDtoDataItemScan


class MailPageDtoDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Mail item id (numeric string).
    """

    folder_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the folder the item is filed in — see `/v1/folders`.
    """

    is_read: bool
    mail_status: str = pydantic.Field()
    """
    Lifecycle status as reported by the mailroom.
    """

    mail_type: str
    sender_name: typing.Optional[str] = None
    recipient_name: typing.Optional[str] = None
    arrival_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the item arrived at the facility.
    """

    envelope_image_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Photo of the item/envelope.
    """

    quarantine_reason: typing.Optional[str] = None
    scan: typing.Optional[MailPageDtoDataItemScan] = pydantic.Field(default=None)
    """
    The scan requested for this item, when one exists.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
