# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mail_detail_dto_folder import MailDetailDtoFolder
from .mail_detail_dto_measurement import MailDetailDtoMeasurement
from .mail_detail_dto_scan import MailDetailDtoScan


class MailDetailDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Mail item id (numeric string).
    """

    is_read: bool
    mail_status: str = pydantic.Field()
    """
    Lifecycle status as reported by the mailroom.
    """

    mail_type: str
    sender_name: typing.Optional[str] = None
    recipient_name: typing.Optional[str] = None
    arrival_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the item arrived at the facility.
    """

    envelope_image_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Photo of the item/envelope.
    """

    quarantine_reason: typing.Optional[str] = None
    scan: typing.Optional[MailDetailDtoScan] = pydantic.Field(default=None)
    """
    The scan requested for this item, when one exists.
    """

    mail_type_label: str = pydantic.Field()
    """
    Human-readable form of `mail_type` (e.g. "Large Letter").
    """

    measurement: MailDetailDtoMeasurement = pydantic.Field()
    """
    Item dimensions, in inches.
    """

    weight: float = pydantic.Field()
    """
    Item weight, in pounds.
    """

    tracking_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Inbound carrier tracking number, when one was captured.
    """

    sender_address: typing.Optional[str] = None
    has_storage_charges: bool = pydantic.Field()
    """
    Whether the item is currently accruing storage charges.
    """

    folder: typing.Optional[MailDetailDtoFolder] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
