# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ScanPageDtoDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Scan id (UUID).
    """

    mail_id: str = pydantic.Field()
    """
    Id of the scanned mail item (numeric string).
    """

    type: str = pydantic.Field()
    """
    `SCAN_REQUEST` (scan the item) or `UNBOXING_REQUEST` (open it and scan the contents).
    """

    status: str = pydantic.Field()
    """
    `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`.
    """

    is_expedited: bool
    instruction: typing.Optional[str] = None
    reject_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the request was rejected. Null unless `status` is `REJECTED`.
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling.
    """

    status_updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the current `status` was reached — for completed scans, the completion time.
    """

    auto_delete_on: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the scan file is permanently deleted — download it before this date. Null when no deletion is scheduled.
    """

    created_at: dt.datetime
    updated_at: dt.datetime = pydantic.Field()
    """
    Last change of any kind — use `status_updated_at` for status timing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
