# This file was auto-generated by Fern from our API Definition.

import typing

ShipmentDetailDtoType = typing.Union[
    typing.Literal["shipment", "return_to_sender", "check_deposit", "pickup"], typing.Any
]
