# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ShipmentDetailDtoMailItemsItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Mail item id (numeric string).
    """

    mail_type: str
    sender_name: typing.Optional[str] = None
    arrival_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the item arrived at the facility.
    """

    envelope_image_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Photo of the item/envelope.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
