# This file was auto-generated by Fern from our API Definition.

import typing

ShipmentDetailDtoStatus = typing.Union[
    typing.Literal["shipped", "in_progress", "payment_failed", "rejected"], typing.Any
]
