# This file was auto-generated by Fern from our API Definition.

import typing

SeedSandboxMailDtoMailType = typing.Union[
    typing.Literal["LETTER", "LARGELETTER", "MAGAZINE", "CATALOG", "SOFTPAK", "PACKAGE"], typing.Any
]
